### ISSUE TITLE
Cyber Engine Tweaks' ZIP file contents changed, placing whole contents inside Cyberpunk 2077\bin\x64 when the root item is the bin folder

### ISSUE THREAD

**Issue by RowanSkie** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#38]
Does someone confirm if other people have the same bug as I am?

**Comment by LittleZen** [comment]
Thank you for the report,

I've notice that too ... sorry I was under exam, I'm gonna investigating on it, I will release a fix as soon as possible <3

**Comment by LittleZen** [comment]
Ok, I've investigated a little bit deeper and I've found the problem: 

In the previous release of the "Cybertweaks" the release of the binary compiled was delivered through a zip file called "Release.zip". 
Seems Yamashi has changed this method, and have introduced the name of the mod instead, that's why the uninstall/install system seems bugged. 

Unfortunately I'm under exam, I will find a solution asap! 

Hope @JayVee732 will join in the topic too, he is the real hero behind the automatic deploy system, maybe he has more information for us!

Z

**Comment by RowanSkie** [comment]
Uh, The problem you're explaining is fixed with 3.2. I've actually checked and the tweaks mod now has a full directory, instead of the files themselves, that's the main problem as it places the whole contents in Cyberpunk 2077/bin/x64, therefore creating another /bin/ folder with the tweaks' files.

**Comment by LittleZen** [comment]
Are you talking about some kind of overwrite problem while the patch is re-installed (guess I've to update my source, or I was working in a old source if this problem has been fixed in 3.2 :/)

**Comment by RowanSkie** [comment]
No, it's just that 3.3 isn't installing the Tweaks properly now. Instead of moving the correct files to Cyberpunk 2077/bin/x64, it now places it on Cyberpunk 2077/bin/x64/bin/x64.

**Comment by LittleZen** [comment]
Ohh ... i've found it now! I'm gonna fix, thank you for the report :D

**Comment by LittleZen** [comment]
@RowanSkie Thank you for the report, this bug should be fixed within the release of the version 3.5! 

Let me know if that worked for you too!

Z

**Comment by RowanSkie** [comment]
Works now!
